[workspace]
resolver = "2"
members = ["projects/*"]
default-members = ["projects/athena-types", "projects/athena-ir", "projects/athena-rewriter", "projects/athena"]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Aster <192607617@qq.com>"]
license = "MPL-2.0"

[workspace.dependencies]
athena-types = { path = "projects/athena-types" }
athena-ir = { path = "projects/athena-ir" }
athena-rewriter = { path = "projects/athena-rewriter" }
athena = { path = "projects/athena" }
num-bigint = { version = "0.4", default-features = false, features = ["std"] }
num-rational = { version = "0.4", default-features = false, features = ["std", "num-bigint"] }
num-traits = "0.2"
libloading = "0.8"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
clap = { version = "4.5.48", features = ["derive"] }
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.3", features = ["full", "extra-traits"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
strip = "symbols"
panic = "abort"
